// Generated by CoffeeScript 1.3.3
var registerCollection, registerModel;

registerModel = function(model, modelname, id) {
  var modelID, modelRef;
  if (id == null) {
    id = void 0;
  }
  modelID = id || model.cid;
  modelRef = model;
  if (!(ss.event.listeners("sync:" + modelname + ":" + modelID).length > 0)) {
    console.log("registering model", modelname);
    return ss.event.on("sync:" + modelname + ":" + modelID, function(msg) {
      return modelRef.trigger("backbone-sync-model", JSON.parse(msg));
    });
  }
};

registerCollection = function(collection, modelname) {
  var collectionRef;
  collectionRef = collection;
  console.log("registering collection", modelname);
  return ss.event.on("sync:" + modelname, function(msg) {
    return collectionRef.trigger("backbone-sync-collection", JSON.parse(msg));
  });
};

window.syncedModel = Backbone.Model.extend({
  sync: function(method, model, options) {
    var modelname, req;
    modelname = this.constructor.modelname;
    next = null;
    if (typeof options.next === "function") {
      next = options.next;
    }
    req = {
      modelname: modelname,
      method: method,
      model: model.toJSON(),
      params: options.params
    };
    if (model.isNew()) {
      req.cid = model.cid;
    }
    console.log("Model upsync", req);
    return ss.backbone(req,next);
  },
  initialize: function(attrs) {
    var deleted, model, modelname;
    modelname = this.constructor.modelname;
    if (!modelname) {
      throw "Cannot sync. You must set the name of the modelname on the Model class";
      delete this;
    }
    model = this;
    registerModel(model, modelname, attrs.id || model.cid);
    deleted = false;
    return this.on("backbone-sync-model", function(res) {
      console.log("Model downsync", modelname, res);
      if (res.e) {
        return console.log(res.e);
      } else {
        if (res.method === "confirm") {
          registerModel(model, modelname, res.model.id);
          this.set(res.model);
        }
        if (res.method === "update") {
          this.set(res.model);
        }
        if (res.method === "delete") {
          if (!deleted) {
            this.trigger("destroy");
          }
          if (this.collection) {
            this.collection.remove(this.id);
          }
          return deleted = true;
        }
      }
    });
  }
});

window.syncedCollection = Backbone.Collection.extend({
  sync: function(method, model, options) {
    var modelname, req,next;
    if (typeof options.next === "function") {
      next = options.next;
    }
    modelname = this.constructor.modelname;

    req = {
      modelname: modelname,
      method: method,
      model: model.toJSON(),
      params: options.params
    };
    console.log("Collection upsync", modelname, req, next);
    return ss.backbone(req, next);
  },
  fetchWhere: function(attributes, options) {
    attributes = attributes || {};
    options = options ? _.clone(options) : {};
    if (options.parse === void 0) options.parse = true;
    var success = options.success;
    var collection = this;
    options.success = function(resp) {
      var method = options.reset ? 'reset' : 'set';
      collection[method](resp, options);
      if (success) success(collection, resp, options);
      collection.trigger('sync', collection, resp, options);
    };
    wrapError(this, options);
    var model = new this.model(attributes);
    return this.sync('read', model, options);
  },
  initialize: function() {
    var collection, modelname;
    modelname = this.constructor.modelname;
    if (!modelname) {
      throw "Cannot sync. You must set the name of the modelname on the Collection class";
      return delete this;
    } else {
      collection = this;
      registerCollection(collection, modelname);
      return this.on("backbone-sync-collection", function(msg) {
        console.log("collection downsync", modelname, msg);
        this.add(msg.models,{parse:true,merge:true});
      });
    }
  }
});
var wrapError = function (model, options) {
  var error = options.error;
  options.error = function(resp) {
    if (error) error(model, resp, options);
    model.trigger('error', model, resp, options);
  };
};

