// Generated by CoffeeScript 1.6.3
var cbStack, defaultCallback, numRequests, ss;

ss = void 0;

ss = require("socketstream");

cbStack = {};

numRequests = 0;

defaultCallback = function(x) {
  return console.log(x);
};

module.exports = function(responderId, config, send) {
  ss.registerApi("backbone", function(req, cb) {
    var msg;
    msg = void 0;
    req.id = ++numRequests;
    if (typeof cb !== "function") {
      cb = defaultCallback;
    }
    cbStack[numRequests] = cb;
    msg = JSON.stringify(req);
    send(msg);
    return void 0;
  });
  return ss.message.on(responderId, function(msg, meta) {
    var obj;
    obj = JSON.parse(msg);
    console.log("responded", msg, obj);
    if (obj.id && cbStack[obj.id]) {
      if (obj.e) {
        console.error("SS-Backbone server error:", obj.e.message);
      } else {
        cbStack[obj.id].apply(cbStack[obj.id], obj.p);
      }
      return delete cbStack[obj.id];
    }
  });
};
