// Generated by CoffeeScript 1.3.3
var ss;

ss = require("socketstream");
var cbStack = {};
var numRequests = 0;
var defaultCallback = function(x) {
  return console.log(x);
};

module.exports = function(responderId, config, send) {
  ss.registerApi("backbone", function(req, cb) {
    // console.log("ss-backbone register", req, cb);
    var msg;
    req.id = ++numRequests;
    if (typeof cb !== 'function') {
      cb = defaultCallback;
    }
    cbStack[numRequests] = cb;

    msg = JSON.stringify(req);
    send(msg);
    return void 0;
  });
  return ss.message.on(responderId, function(msg, meta) {
    obj = JSON.parse(msg);
    console.log("responded",msg, obj);
    if (obj.id && cbStack[obj.id]) {
      if (obj.e) {
        console.error('SS-Backbone server error:', obj.e.message);
      } else {
        cbStack[obj.id].apply(cbStack[obj.id], obj.p);
      }
      delete cbStack[obj.id]
    }
  });
};
